# Generated by Django 5.0.3 on 2024-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlModel',
            fields=[
                ('url', models.CharField(max_length=700)),
                ('miniurl', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
