# Generated by Django 5.0.3 on 2024-03-27 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
