# Generated by Django 5.0.3 on 2024-03-28 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_remove_urlmodel_date_urlmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='url',
            field=models.URLField(max_length=700),
        ),
    ]
